<?php

namespace DcD\RestBundle\Repository;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\EntityRepository;

/**
 * BasketItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketItemRepository extends EntityRepository
{
    /**
     * get all basketItems that are belongs to a basket
     * implemented to avoid lazy loading always the basket entity
     *
     * @param $basketId
     * @return array
     */
    public function getItems($basketId)
    {
        return $this->getEntityManager()->createQuery('
            SELECT 
              bi.id, 
              bi.info
            FROM 
              RestBundle:BasketItem bi
              JOIN bi.basket b
            WHERE 
              bi.basket = :id AND 
              bi.isDeleted = 0 AND 
              b.isDeleted = 0
         ')
            ->setParameter('id', $basketId)
            ->getResult();
    }

    /**
     * get one basketItem
     * implemented to avoid lazy loading always the basket entity
     *
     * @param $basketItemId
     * @return array
     */
    public function getItem($basketItemId)
    {
        return $this->getEntityManager()->createQuery('
            SELECT 
              bi.id, 
              bi.info 
            FROM 
              RestBundle:BasketItem bi 
              JOIN bi.basket b
            WHERE 
              bi.id = :id AND 
              bi.isDeleted = 0 AND
              b.isDeleted = 0
         ')
            ->setParameter('id', $basketItemId)
            ->getOneOrNullResult(AbstractQuery::HYDRATE_ARRAY);
    }
}
