<?php

namespace DcD\RestBundle\Repository;

/**
 * BasketItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketItemRepository extends \Doctrine\ORM\EntityRepository
{
}
