<?php

namespace DcD\RestBundle\Repository;
use Doctrine\ORM\AbstractQuery;

/**
 * BasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasketRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all basket + basketItems
     * implemented to get FieldNames instead EntityName
     * and to run only one query instead of many more
     *
     * @return array
     */
    public function getBaskets()
    {
        return $this->getEntityManager()->createQuery('
            SELECT 
               b, bi
            FROM 
              RestBundle:Basket b 
              LEFT JOIN b.basketItems bi
            WHERE
              b.isDeleted = 0
            
         ')
            ->getResult(AbstractQuery::HYDRATE_ARRAY);
    }

    /**
     * Get one complete basket + basketItems
     * implemented to get FieldNames instead EntityName
     *
     * @param $basketId
     * @return array
     */
    public function getBasket($basketId)
    {
        return $this->getEntityManager()->createQuery('
            SELECT 
               b, bi
            FROM 
              RestBundle:Basket b 
              LEFT JOIN b.basketItems bi  
            WHERE 
              b.id = :id AND            
              b.isDeleted = 0
         ')
            ->setParameter('id', $basketId)->getOneOrNullResult(AbstractQuery::HYDRATE_ARRAY);
    }

}
